# -*- coding: utf-8 -*-
"""contoh variabel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15F3zfASQYdu35ayNVfUkOwYgYkT07TGk
"""

#Contoh Variabel
a = 5
print(a)